# Estructuras básicas de python


In [15]:
# listas
zeros = [0, 0, 0, 0, 0]
unos = [1, 1, 1, 1, 1]
zer_uno = [0, 1, 0, 1, " "]




In [5]:
#dict
persona = {
    'nombre': 'Luis Alberto Spinetta',
    'nacimiento': '23 January 1950',
    'muerte': '8 February 2012 ',
    'edad': 62,
    'profesion': 'músico',
    'albúm':'Durazno Sangrando'
}
persona

{'albúm': 'Durazno Sangrando',
 'edad': 62,
 'muerte': '8 February 2012 ',
 'nacimiento': '23 January 1950',
 'nombre': 'Luis Alberto Spinetta',
 'profesion': 'músico'}

In [ ]:
#tuplas
t1 = ('la', 'luz')
t2 = ('se', 'duerme')


# Ciclos y estructuras de control

In [6]:
#if 
if zeros[0] == 0:
    print("El valor dado es cero: {}".format(zeros[0]))
    

El valor dado es cero: 0


In [11]:
#for 
for dato, valor in persona.items():
    print("{}: {}".format(dato, valor))    

profesion: músico
nombre: Luis Alberto Spinetta
muerte: 8 February 2012 
albúm: Durazno Sangrando
nacimiento: 23 January 1950
edad: 62


In [17]:
#if elif else - for 
for num in zer_uno:
    if num == 0:
        print("El valor dado es cero: {}".format(num))
    elif num == 1:
        print("El valor dado es 1: {}".format(num))
    else:
        print("El valor dado no es ni cero ni uno: {}".format(num))

El valor dado es cero: 0
El valor dado es 1: 1
El valor dado es cero: 0
El valor dado es 1: 1
El valor dado no es ni cero ni uno:  


In [20]:
# funciones

def func_profesion(persona):
    return persona['profesion']

func_artista(persona)

'músico'

# numpy

In [21]:
# importar la librería numpy como np
import numpy as np

In [39]:
#array
zeros_np = np.array(zer_uno)
zeros_np


array(['0', '1', '0', '1', ' '], dtype='<U21')

In [38]:
# tamaño
zeros_np.shape

(5,)

In [24]:
#zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
#números seudo aleatorios de la libería np, modulo random, función randint
2.5 * (np.random.randint(5, size=(5,)) - 1) / 4.

array([0.625, 0.   , 0.   , 0.625, 1.25 ])

In [36]:
# números aleatorios de la dist normal
2.5 * np.random.randn(2, 4) + 3

array([[ 6.30134836,  3.35300683,  1.12557006,  6.32945979],
       [ 3.74163612,  2.82874308,  2.12035139, -1.16471942]])

# pandas 